"
notice: Copyright 2010-2013 Cincom Systems, Martin Kobetic and Michael Lucas-Smith
category: description - actions
"
postLoadAction
    Smalltalk loadPackage: 'stx:goodies/xtreams/support/tests'.
    Smalltalk loadPackage: 'stx:goodies/xtreams/core/tests'.
    Smalltalk loadPackage: 'stx:goodies/xtreams/terminals/tests'.
    Smalltalk loadPackage: 'stx:goodies/xtreams/transforms/tests'.
    Smalltalk loadPackage: 'stx:goodies/xtreams/substreams/tests'.

    "Created: / 20-03-2013 / 18:58:48 / Jan Vrany <jan.vrany@fit.cvut.cz>"
